<?

defined('_JEXEC') or die;

$app = JFactory::getApplication();
$doc = JFactory::getDocument();

// remove the "generated by joomla" meta tag
unset($doc->_generator);

include_once('includes/functions.php');

include_once('includes/process_comments.php');

include_once('includes/check_for_component_pages.php');

// include_once('includes/are_you_coming_from_search.php');

include_once('includes/redirect_bad_urls.php');

// include_once('includes/log_ip_address_activity.php');

include_once('includes/onboardingemail.php');

include('includes/block_users_by_ip.php');



if ( isset($_SERVER['HTTPS']) || $_SERVER['HTTPS'] == 'on' ) {
    header("Location: http://www.inmotionhosting.com/support/");
}

$cdn_subdomain = return_cdn_subdomain();


// Same as error_reporting(E_ALL);
ini_set('error_reporting', E_ALL);
// Report all PHP errors
error_reporting(-1);

// Add Stylesheets
if("minify" == "minify")
{
$doc->addStyleSheet("https://inmotionhosting.com/support/templates/supportcentertemplate/css/temp.css?v=2016053108");
//        $doc->addStyleSheet("//$cdn_subdomain/support/templates/supportcentertemplate/css/minified.a.css?v=201501161003");
//	$doc->addStyleSheet("//$cdn_subdomain/support/templates/supportcentertemplate/css/minified.a.css?v=201409290926");
	$doc->addStyleSheet($this->baseurl . '/media/jui/css/bootstrap-responsive.css?v=2016011214');
	$doc->addScript('/support/templates/' . $this->template  . '/js/css3-mediaqueries.js');
}
else
{
	$doc->addStyleSheet('/assets/css/styles.css');
	// $doc->addStyleSheet('/support/templates/'.$this->template.'/css/styles.css');
	$doc->addStyleSheet('/support/templates/'.$this->template.'/css/style.css?v=201308080957');
	// $doc->addStyleSheet('/support/templates/'.$this->template.'/css/combined_20130315.css');
}





if("combined" == "combined")
{
	// unset( $doc->_scripts );
	// $doc->addScript('/support/templates/' . $this->template . '/js/combined.js?v=201402041536', 'text/javascript');

	foreach($doc->_scripts as $k => $v)
                unset($doc->_scripts[$k]);
}
else
{
	// Add Javascript
	// unset( $doc->_scripts );
	
	$doc->addScript('/js/libs/modernizr-2.5.3-respond-1.1.0.min.js', 'text/javascript');
#	$doc->addScript('/support/media/jui/js/jquery.min.js', 'text/javascript');
	$doc->addScript('/support/media/jui/js/jquery-noconflict.js', 'text/javascript');
//$doc->addScript('/support/templates/' . $this->template . '/js/combined_201303154pm.js', 'text/javascript');
    $doc->addScript('/support/templates/' . $this->template . '/js/fancybox.js', 'text/javascript');
    $doc->addScript('/support/templates/' . $this->template . '/js/combined.js.old', 'text/javascript');
}






$user = JFactory::getUser();

if ($user->groups[8] == 8 AND isset($_POST['cxs_check_task']))
	include_once('includes/cxs_checks.php');






$joption = JRequest::getVar('option'); $jview = JRequest::getVar('view'); $jid = JRequest::getVar('id');

$this_is_support_center_homepage = false;
if( $joption == "com_content" AND $jview == "categories" AND $jid == 0)
	$this_is_support_center_homepage = true;






// ------------------------------------------------------------------------------------------------
// canonical urls
// ------------------------------------------------------------------------------------------------
// article category
if( $joption == "com_content" AND $jview == "category" )
{
	$canonical_url = "http://www.inmotionhosting.com" . JRoute::_(ContentHelperRoute::getCategoryRoute($jid));
	$doc->addHeadLink($canonical_url, 'canonical');
}






// ------------------------------------------------------------------------------------------------
// chat buttons
// ------------------------------------------------------------------------------------------------
// livechat settings first
// ------------------------------------------------------------------------------------------------
$jsLaunchChat = "launchChat";
$which_chat = "livechat";
$launch_chat_text = "Support Chat";
// then boldchat settings
// ------------------------------------------------------------------------------------------------
$boldchat_wdid = "2034694302371522916";
$boldchat_brand = "InMotion";
if( $_GET['chat_version'] == "boldchatsupport" OR "enable" == "enable")
{
	$launch_chat_text = "Support Chat";
	$jsLaunchChat = "launchBoldChat";
	$boldchat_cwdid = "4729630034290649077";
	$boldchat_rdid = "2324923566971164486";
	$boldchat_popup_name = "Chat8718689652968401074";
	$boldchat_url_to_open_with_js = "https://www.inmotionhosting.com/support/launch-chat/?rdid=$boldchat_rdid";
	$which_chat = "boldchat";
}
if( $_GET['chat_version'] == "boldchatsupporttraining" )
{
	$launch_chat_text = "Support Chat Training";
	$jsLaunchChat = "launchBoldChat";
	$boldchat_cwdid = "2186789702930697388";
	$boldchat_rdid = "708918024841625095";
	$boldchat_popup_name = "Chat1049429156724697770";
	$boldchat_url_to_open_with_js = "https://www.inmotionhosting.com/support/launch-chat/?rdid=$boldchat_rdid";
	$which_chat = "boldchat";
}
// Sales - blank department chosen
if( $_GET['chat_version'] == "boldchatsales" )
{
	$launch_chat_text = "Sales Chat";
	$jsLaunchChat = "launchBoldChat";
	$boldchat_cwdid = "1297007483490870228";
	$boldchat_rdid = "";
	$boldchat_popup_name = "Chat4007240738274498641";
	$boldchat_url_to_open_with_js = "https://livechat.boldchat.com/aid/370246676985295205/bc.chat?resize=true&cwdid=$boldchat_cwdid&wdid=$boldchat_wdid&vr=&vn=&vi=&ve=&vp=&iq=&curl=&brand=$boldchat_brand";
	$which_chat = "boldchat";
}
if( $_GET['chat_version'] == "boldchatsalestraining" )
{
	$launch_chat_text = "Sales Chat Training";
	$jsLaunchChat = "launchBoldChat";
	$boldchat_cwdid = "5848516531813174403";
	$boldchat_rdid = "794814027115867494";
	$boldchat_popup_name = "Chat4842050459426617828";
	$boldchat_url_to_open_with_js = "https://livechat.boldchat.com/aid/370246676985295205/bc.chat?resize=true&cwdid=$boldchat_cwdid&wdid=$boldchat_wdid&rdid=$boldchat_rdid&vr=&vn=&vi=&ve=&vp=&iq=&curl=&brand=$boldchat_brand";
	$which_chat = "boldchat";
}






?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
 <script src="/support/templates/supportcentertemplate/js/main.js?v=201605261319" type="text/javascript"></script>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>


<?php php_uname("n"); ?>



  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width" />

<?
	if ( !  $this->error )
	{
?>
		<jdoc:include type="head" />
<?
	}
	else
	{
		/*
		echo "
			<link rel='stylesheet' href='/support/templates/" . $this->template . "/css/styles.css' type='text/css' />
			<link rel='stylesheet' href='/support/templates/" . $this->template . "/css/style.css' type='text/css' />
		";
		*/
		echo "<link rel='stylesheet' href='/support/templates/" . $this->template . "/css/minified.a.css?v=201409290926' type='text/css' />";
	}
?>


		



	<script type="text/javascript">
		(function() {
			var config = {
				kitId: 'tkh8ukm',
				scriptTimeout: 3000
			};
			var h=document.getElementsByTagName("html")[0];h.className+=" wf-loading";var t=setTimeout(function(){h.className=h.className.replace(/(\s|^)wf-loading(\s|$)/g," ");h.className+=" wf-inactive"},config.scriptTimeout);var tk=document.createElement("script"),d=false;tk.src='//use.typekit.net/'+config.kitId+'.js';tk.type="text/javascript";tk.async="true";tk.onload=tk.onreadystatechange=function(){var a=this.readyState;if(d||a&&a!="complete"&&a!="loaded")return;d=true;clearTimeout(t);try{Typekit.load(config)}catch(b){}};var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(tk,s)
		})();
	</script>






	<? include_once("includes/ga_by_author.php"); ?>






	<?
		// 2014.01.08 13:39 - track hits by article's publish year/month
		$track_hits_by_month_published = "";
		if( $joption == "com_content" AND $jview == "article" )
			$track_hits_by_month_published = "_gaq.push(['_setCustomVar', 4, 'DateMonthPublished', '" . date('Y-m',strtotime($article->publish_up)) . "', 3]);\n";

		// 2014.05.07 - track hits by article's modified year/month
                $track_hits_by_month_modified = "";
                if( $joption == "com_content" AND $jview == "article" )
                        $track_hits_by_month_modified = "_gaq.push(['_setCustomVar', 3, 'DateMonthModified', '" . date('Y-m',strtotime($article->modified)) . "', 3]);\n";

		// bradm 2014.07.10.1033 - no need to track all this stuff right now
		/*
		// 2014.06.27 - track how many comments on an article
                $track_hits_by_comment_count = "";
		// $track_hits_by_word_count = "";
                if( $joption == "com_content" AND $jview == "article" AND is_numeric($jid))
		{
			$query = "SELECT count(`id`) FROM #__comments WHERE `object_group` = 'com_content' AND `object_id` = $jid;";
			$db->setQuery($query);
			$comment_count = $db->loadResult();
                        $track_hits_by_comment_count = "_gaq.push(['_setCustomVar', 2, 'CommentCount', '$comment_count', 3]);\n";

			// $article_word_count = strip_tags($article->introtext);
			// $article_word_count = str_word_count($article_word_count);
			// $track_hits_by_word_count = "_gaq.push(['_setCustomVar', 1, 'WordCount', '$article_word_count', 3]);\n";
		}

		// 2014.07.02 - track unique words
		$track_hits_by_unique_word_count = "";
		if( $joption == "com_content" AND $jview == "article" AND is_numeric($jid))
		{
			$unique_article_word_count = strip_tags($article->introtext);
		        $unique_article_word_count = strtolower($unique_article_word_count);
		        $unique_article_word_count = str_word_count($unique_article_word_count,1);
		        $unique_article_word_count = array_unique($unique_article_word_count);
		        //echo "<pre>"; print_r($unique_article_word_count); echo "</pre>";
		        //echo "<pre>" . count($unique_article_word_count); echo "</pre>";
			$track_hits_by_unique_word_count = "_gaq.push(['_setCustomVar', 1, 'UniqueWordCount', 'gauwc" . count($unique_article_word_count) . "', 3]);\n";
		}
		*/
	?>






	<!-- GA Code - www.inmotionhosting.com -->
	<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-1501988-1']);
		<? // echo $track_hits_by_unique_word_count; ?>
		<? // echo $track_hits_by_word_count; ?>
		<? // echo $track_hits_by_comment_count; ?>

		<? echo $track_hits_by_month_modified; ?>
		<? echo $track_hits_by_month_published; ?>
		_gaq.push(['_setCustomVar', 5, 'Author', '<? echo $ga_author; ?>', 3]);
		_gaq.push(['_trackPageview']);

		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
	</script>






	<?	// --------------------------------------------------------------------------------
		// 2013.12.20 - boldchat
		// --------------------------------------------------------------------------------
	?>	






	<link rel="shortcut icon" href="//imh01-inmotionhosting1.netdna-ssl.com/img/imh_favicon_hd.png" type="image/x-icon" />






	<?
		if( $_GET['test'] == "prettify" )
			echo "<script src='/support/templates/supportcentertemplate/pf/run_prettify.js'></script>";
	?>






	<?
		// 2014.02.19.0759 - bradm
		// flag this page to make it easier to find an clear the cache
		echo "<!-- cid:" . md5($_SERVER['REQUEST_URI']) . " -->";
	?>






	<?
		if( $_GET['test'] == "main_article_nav" )
		{
			echo "
			<style>
				#main_article_nav {}
				#main_article_nav.sticky{position:fixed;width:675px;top:0px;left:auto;right:auto;;z-index:99999;background:#f9f9f9;margin-top:-1px;padding-bottom:5px;border: 1px solid #ddd}
			</style>
			<script type='text/javascript'>
				jQuery(function(){  
					jQuery(window).scroll(function(){  
						if (jQuery(window).scrollTop() > 350) {  
							jQuery('#main_article_nav').addClass('sticky');
						} else {  
							jQuery('#main_article_nav').removeClass('sticky');
						}  
					});  
				});
			</script>
			";
		}
	?>



<script src='https://www.google.com/recaptcha/api.js' async defer></script>

<!-- facebook pixel -->
<script>(function(){
   window._fbds = window._fbds || {};
   _fbds.pixelId = 411832918961118;
   var fbds = document.createElement('script');
   fbds.async = true;
   fbds.src = '//connect.facebook.net/en_US/fbds.js';
   var s = document.getElementsByTagName('script')[0];
   s.parentNode.insertBefore(fbds, s);
 })();
 window._fbq = window._fbq || [];
 window._fbq.push(["track", "PixelInitialized", {}]);
 </script>
 <noscript><img height="1" width="1" border="0" alt="" style="display:none"
 src="https://www.facebook.com/tr?id=411832918961118&amp;ev=NoScript"
 /></noscript>
 
 
 
<style>
@media all and (max-width: 1024px) {
    .main-sc-left { width:100%; }
}

</style> 
 
 
<style>
	div.item-page h2 {
		border:0px;
		font-size:20px;
		font-weight:bold;
	}
	div.item-page h3 {
		border:0px;
	}
	a.btn.small {
		font-size:12px;
		padding:0px 5px;
		text-transform:none;
	}
	
	button.btn.btn-success,
	input.btn.btn-success,
	a.btn.btn-success.small {
		box-shadow:0 3px 0 #387038;
	}
	.floatingNav { 
			display: none; 
			border: 2px solid;
			border-radius: 25px;
		}
</style>






</head>
<body>
<!-- Qualaroo for inmotionhosting.com -->
<!-- Paste this code right after the <body> tag on every page of your site. -->
<script type="text/javascript">
  var _kiq = _kiq || [];
  (function(){
    setTimeout(function(){
    var d = document, f = d.getElementsByTagName('script')[0], s = d.createElement('script'); s.type = 'text/javascript';
    s.async = true; s.src = '//s3.amazonaws.com/ki.js/56452/cuH.js'; f.parentNode.insertBefore(s, f);
    }, 1);
  })();
</script>


<link rel="stylesheet" href="/support/templates/supportcentertemplate/js/fancyBox/source/jquery.fancybox.css?v=2.1.5" type="text/css" media="screen" />
<script type="text/javascript" src="/support/templates/supportcentertemplate/js/fancyBox/source/jquery.fancybox.pack.js?v=2.1.5"></script>


<script type="text/javascript">
                    var launchBoldChat = function() {
                window.open('<? echo $boldchat_url_to_open_with_js; ?>&url=' + escape(document.location.href), '<? echo $boldchat_popup_name; ?>', 'toolbar=0,scrollbars=1,location=0,statusbar=0,menubar=0,resizable=1,width=640,height=650');

                        <? echo $google_set_account_by_author . "\n"; ?>
                        _gaq.push(['_trackEvent', 'chat-by-ip', 'launch-by-ip', '<? echo $_SERVER['HTTP_X_FORWARDED_FOR']; ?>']);

                        _gaq.push(['_setAccount', 'UA-1501988-1']);
                        _gaq.push(['_trackEvent', 'chat', 'launch', 'support center']);
                        _gaq.push(['_trackEvent', 'chat-by-ip', 'launch-by-ip', '<? echo $_SERVER['HTTP_X_FORWARDED_FOR']; ?>']);
                        trackAnchorClickSC("trackAnchorClickChatSC");
            }
        </script>


<!-- ClickTale Top part -->
<script type="text/javascript">
var WRInitTime=(new Date()).getTime();
</script>
<!-- ClickTale end of Top part -->



	<a name='top-of-page'></a>

<!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

  <div id="skip">
    <a href="#main">Skip to Main Content</a>
    <a href="#nav">Skip to Navigation</a>
    </div>
  
<header role="banner">
        <div class="container">
            <div class="row">
                <a href="/" class="span3"><img class='imhLogo' src="//<? echo $cdn_subdomain; ?>/img/logo-imh.png" alt="InMotion Hosting" /></a>
		<div class="span6 offset3">
			<ul class="nav nav-pills nav-pills-contact pull-right contactListHeader">
				<li class="pull-right sales-label">Questions? Contact Support:</li>
<?php /*if( $this_is_support_center_homepage == true ) {
echo "<li class='no-margin clear'><a class='no-margin chat' onclick='$jsLaunchChat();_gaq.push([‘_trackEvent’, ‘External Link’, ‘Home Page Chat’]); return false;' rel='nofollow'><i class='icon-chat'></i>$launch_chat_text</a></li>"; } else {*/?>
				<li class="no-margin clear"><a class="no-margin chat" onclick="<? echo $jsLaunchChat; ?>();return false;" rel='nofollow'><i class="icon-chat"></i> <? echo $launch_chat_text; ?></a></li> <? #} ?>
                <li class="no-margin"><a class="no-margin chat" href="/skype" onclick="window.open(this.href,'_blank', 'location=yes,height=500,width=600,scrollbars=no,status=yes'); return false;" rel='nofollow'><i style="height: 22px; width: 22px; margin-top: -2px;" class="icon-skype"></i>SKYPE</a></li>
				<li class="nav-pills-no-link no-margin"><i class="icon-phone"></i> 888.321.HOST(4678)</li>
			</ul>
		</div>
            </div>
        </div>
    </header>
    <?php include 'includes/nav.php' ?>

  
    <div id="main" class="main-container" role="main" style='background:#f9f9f9;'>

	<div style="background:url('//<? echo $cdn_subdomain; ?>/img/rednoise.gif');">
		<div class='container'>
			<img src='/support/templates/supportcentertemplate/images/logo.png.old?v=201507291301' class='MainLogo' usemap='#sclogo' />
			<map name='sclogo'><area shape='rect' coords='130,25,430,60' href='/support' alt='InMotion Hosting Support Center'></map>
			<form action="/support/search" method="get" class="form-inline red_header_dsf" id="search_in_header" name="search_in_header">
	 		<input name="searchword" id="mod-search-searchword" maxlength="80"  class="inputbox search-query" type="text" size="20" value="How may we help?"  onblur="if (this.value=='') this.value='How may we help?';" onfocus="if (this.value=='How may we help?') this.value='';" /> <button class="button btn btn-info" onclick="this.form.searchword.focus();" style='display:inline-block; width:80px; border-radius:3px; height:32px; line-height:22px; margin:0px;'>Search</button>
			 </form>
		</div>
	</div>

	<div class='container' style='background:#f3f3f3;'>
		<div style='margin:0px; margin-left:auto; margin-right:auto; position:relative;'>
			<jdoc:include type="modules" name="position-bc" style="none" />
		</div>
	</div>



<?  /*
//Grab URL
$url = 'http://' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];

// IF URL has edu/ in it

if (strpos($url,'edu/') !== false) {


// Grab globals from bottom edu nav
global $prev_page_title;
global $prev_page_url;
global $next_page_title;
global $next_page_url;

if (empty($next_page_title) AND empty($prev_page_title)){
}
else {
echo "<div style='height:54px;width:700px;margin-right:auto;margin-left:auto;'>";
}

//Prev Button
if (!empty($prev_page_title)) {

echo '<a href="';
echo "$prev_page_url";
echo '">';
echo "<div id='edu_button' style='margin: 5px 5px; float:left;width:231px;height:54px;background-image:url(/support/templates/supportcentertemplate/images/edu/prev-button.png);'>";
echo "<div id='edu_text' style='float:right;width:160px;position: relative;top: 50%;transform: translateY(-50%);'><font size='1' color='white'>";
echo $prev_page_title;
echo "</font></div> </div></a>";
}
//Next Button
if (!empty($next_page_title)) {
echo '<a href="';
echo "$next_page_url";
echo '">';
echo "<div id='edu_button' style='margin: 5px 5px; float:right;width:231px;height:54px;background-image:url(/support/templates/supportcentertemplate/images/edu/next-button.png);'>";
echo "<div id='edu_text' style='margin-left:3px;float:left;width:160px;position: relative;top: 50%;transform: translateY(-50%);'><font size='1' color='white'>";
echo "$next_page_title";
echo "</font></div> </div></a>";
}
if (empty($next_page_title) AND empty($prev_page_title)){
}
else {

echo "</div>";
}}
*/
?>



<?
	/**
	 * Which layout are we using for the main content?
	 */
	if(
		// support/onboarding
		($joption == "com_content" AND $jview == "category" AND $jid == 513)
	)
		include_once("layout_maincontent_1col.php");
	else
		include_once("layout_maincontent_2col.php");






	/**
	 * Put comments into their own div
	 */
	if (	( !  $this->error ) AND								/* if this isn't an error page */
		( $joption == "com_content" AND $jview == "article" AND is_numeric($jid) ) AND	/* if this is an article */
		( $jid != 3283 )								/* don't show comments on "join the community!" page */
	)
		include_once('includes/fixComments.php');
?>






	<div style="background:url('//<? echo $cdn_subdomain; ?>/img/pattern.gif');padding-top:20px;">
		<div style=' margin:0px; padding:10px 0px 10px 0px; margin-left:auto; margin-right:auto;'>
			<? include_once('includes/need_more_help.php'); ?>
		</div>
	</div>
  
  
    <span class=""></span>
<footer role="contentinfo" class="wrap">
        <div class="container">
            <div class="row-fluid">
                <ul class="nav nav-list span2">
                    <li class="nav-header">Web Hosting</li>
                    <li><a href="/business-hosting">Business Hosting</a></li>
                    <li><a href="/vps-hosting">VPS Hosting</a></li>
                    <li><a href="/dedicated-servers">Dedicated Servers</a></li>
                    <li><a href="/enterprise-hosting-solutions">Enterprise Hosting Solutions</a></li>
                    <li><a href="/reseller-hosting">Reseller Hosting</a></li>
                    <li><a href="/wordpress-hosting">WordPress Hosting</a></li>
                    <li><a href="/launch-assist">Launch Assist™</a></li>
                    <li><a href="/managed-hosting">Managed Hosting</a></li>
                    <li><a href="/domains">Domain Names</a></li>
                    <li><a href="/webdesign">Web Design Services</a></li>
                </ul>
                <ul class="nav nav-list span2">
                    <li class="nav-header">Hosting Features</li>
                    <li><a href="/ssd-hosting">SSD Hosting</a></li>
                    <li><a href="/shared-cpanel-hosting">Shared cPanel Hosting</a></li>
                    <li><a href="/ecommerce-hosting">eCommerce Hosting</a></li>
                    <li><a href="/ssh-hosting">SSH Hosting</a></li>
                    <li><a href="/ruby-hosting">Ruby Hosting</a></li>
                    <li><a href="/postgresql-hosting">PostgreSQL Hosting</a></li>
                    <li><a href="/cheap-hosting">Cheap Hosting</a></li>
                    <li><a href="/cheap-dedicated-servers">Cheap Dedicated Servers</a></li>
                    <li><a href="/transfer-your-website-to-the-best-web-hosting">Transfer Websites</a></li>
                </ul>
                <ul class="nav nav-list span2">
                    <li class="nav-header">Hosting Tools</li>
                    <li><a href="/wordpress-hosting">WordPress</a></li>
                    <li><a href="/joomla-hosting">Joomla</a></li>
                    <li><a href="/drupal-hosting">Drupal</a></li>
                    <li><a href="/host-with-cpanel">cPanel</a></li>
                    <li><a href="/prestashop-hosting">PrestaShop</a></li>
                    <li><a href="/moodle-hosting">Moodle</a></li>
                    <li><a href="/opencart-hosting">OpenCart</a></li>
                    <li><a href="/boldgrid-website-builder">BoldGrid<span class="white"> *NEW*</span></a></li>
                </ul>
                <ul class="nav nav-list span2">
                    <li class="nav-header">Community</li>
                    <li><a href="/premier-support">Premier Support ™</a></li>
                    <li><a href="http://www.inmotionhosting.com/support">Support Center</a></li>
                    <li><a href="/hosting-affiliate-program">Host Affiliate</a></li>
                    <li><a href="/infographics">Web Hosting Infographics</a></li>
                    <li><a href="/los-angeles-web-hosting">Los Angeles Hosting</a></li>
                    <li><a href="/meet-us/go-green">Green Data Centers</a></li>
                    <li><a href="http://www.inmotionhosting.com/edu">Student Web Hosting</a></li>
                    <li><a href="/partners">Partners</a></li>
                </ul>
                <ul class="nav nav-list span2">
                    <li class="nav-header">About Us</li>
                    <li><a href="/contact">Contact Us</a></li>
                    <li><a href="/terms-of-service">Terms of Service</a></li>
                    <li><a href="/privacy-policy">Privacy Policy</a></li>
                    <li><a href="http://www.inmotionhosting.com/blog">Blog</a></li>
                    <li><a href="/guarantee">Guarantee</a></li>
                    <li><a href="/testimonials">Testimonials</a></li>
                    <li><a href="http://www.inmotionhosting.com/employment">We're Hiring</a></li>
                    <li><a href="/sitemap">Site Map</a></li>
                    <li><a href="/press">Press</a></li>
                </ul>

                <div class="span2 column-main">
                    <div class="row-fluid">
                        <div class="span10 offset2">
                            <p class="stay-in-touch">Stay in touch on</p>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                            <ul class="ft-iconlist">
                                <li><a href="https://plus.google.com/+inmotionhosting/posts"><img src="/img/icon-google.png" alt="InMotion Hosting on Google+"></a></li>
                                <li><a href="https://twitter.com/inmotionhosting"><img src="/img/icon-twitter.png" alt="InMotion Hosting on Twitter"></a></li>
                                <li><a href="https://www.facebook.com/inmotionhosting"><img src="/img/icon-facebook.png" alt="InMotion Hosting on Facebook"></a></li>
                                <li><a href="https://www.youtube.com/user/InMotionSupport"><img src="/img/icon-youtube-text.png" alt="InMotion Hosting on YouTube"></a></li>
                                <li><a href="https://www.linkedin.com/company/inmotion-hosting"><img src="/img/icon-linkedin.png" alt="InMotion on LinkedIn"></a></li>
                            </ul>
                        </div>
                    </div>
                    <div itemscope="" itemtype="http://schema.org/LocalBusiness">
                        <span class="ft-logo pull-right"> <a href="/"><img src="//imh01-inmotionhosting1.netdna-ssl.com/img/footer-logo.svg" alt="InMotion Hosting" class="logosize-foot"></a></span>
                        <p class="address" itemprop="address" itemscope="" itemtype="http://schema.org/PostalAddress">
                        <span itemprop="streetAddress">6100 Center Drive, Suite 1190</span><br>
                        <span itemprop="addressLocality" class="city">Los Angeles</span>, <span itemprop="addressRegion" class="state">CA</span> <span itemprop="postalCode" class="postalcode">90045</span><br>
                        <span itemprop="telephone">
                            888.321.HOST(4678)                        </span><br>
                        <span>2016 © All Rights Reserved</span></p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</div> <!-- #Main End -->
<div style='display:none;'><? include_once('includes/set_cookies.php'); ?></div>






<?

if( $_SERVER['HTTP_X_FORWARDED_FOR'] == "216.54.31.86"  )
{
	// include_once('includes/support_wiki.php');
}

include_once("includes/onboarding_popups.php");



?>





<?
// -------------------------------------------------------------------------------------------------------
// 2013.12.02 - bradm
// BOLDCHAT Visitor Monitor HTML
// -------------------------------------------------------------------------------------------------------
if( $_GET['chat_version'] == "boldchat" OR $which_chat == "boldchat" )
{

	if($user->username == "BradM" OR substr_count($_SERVER['REQUEST_URI'],"changing-mambo-appearance/creat-new-menu")>0 )
	{
?>
<!-- BoldChat Visitor Monitor HTML v4.00 (Website=InMotion Hosting,ChatButton=- None -,ChatInvitation=BradM1) -->
<script type="text/javascript">
  var _bcvma = _bcvma || [];
  _bcvma.push(["setAccountID", "370246676985295205"]);
  _bcvma.push(["setParameter", "WebsiteDefID", "2034694302371522916"]);
  _bcvma.push(["setParameter", "InvitationDefID", "2952821345566374405"]);
  _bcvma.push(["pageViewed"]);
  (function(){
    var vms = document.createElement("script"); vms.type = "text/javascript"; vms.async = true;
    vms.src = ('https:'==document.location.protocol?'https://':'http://') + "vmss.boldchat.com/aid/370246676985295205/bc.vms4/vms.js";
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(vms, s);
  })();
</script>
<noscript>
<a href="http://www.boldchat.com" title="Live Support" target="_blank"><img alt="Live Support" src="https://vms.boldchat.com/aid/370246676985295205/bc.vmi?wdid=2034694302371522916" border="0" width="1" height="1" /></a>
</noscript>
<!-- /BoldChat Visitor Monitor HTML v4.00 -->
<?
	}
	else
	{
?>
<!-- BoldChat Visitor Monitor HTML v4.00 (Website=InMotion Hosting,ChatButton=- None -,ChatInvitation=My Invite Ruleset) -->
<script type="text/javascript">
  var _bcvma = _bcvma || [];
  _bcvma.push(["setAccountID", "370246676985295205"]);
  _bcvma.push(["setParameter", "WebsiteDefID", "2034694302371522916"]);
  _bcvma.push(["setParameter", "InvitationDefID", "367054575182333368"]);
  _bcvma.push(["pageViewed"]);
  (function(){
    var vms = document.createElement("script"); vms.type = "text/javascript"; vms.async = true;
    vms.src = ('https:'==document.location.protocol?'https://':'http://') + "vmss.boldchat.com/aid/370246676985295205/bc.vms4/vms.js";
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(vms, s);
  })();
</script>
<noscript>
<a href="http://www.boldchat.com" title="Live Support" target="_blank"><img alt="Live Support" src="https://vms.boldchat.com/aid/370246676985295205/bc.vmi?wdid=2034694302371522916" border="0" width="1" height="1" /></a>
</noscript>
<!-- /BoldChat Visitor Monitor HTML v4.00 -->
<?
	}

}
?>






<a href='http://www.inmotionhosting.com/support/tob-a-uoy-era' style='display:none;' rel='nofollow'>Post a Comment</a>






<?

/*
if ($_GET['test'] == "servera")
{
	flush();
	echo "<pre>- - -\n"; print_r($_SERVER); echo "</pre>";
	$headers = apache_request_headers();
	echo "<pre>- - -\n"; print_r($headers); echo "</pre>";
	$headers = headers_list();
	echo "<pre>- - -\n"; print_r($headers); echo "</pre>";
	var_dump(headers_list());
	$headers = apache_response_headers();
	echo "<pre>- - -\n"; print_r($headers); echo "</pre>";
}
*/

/*
if($_GET['test'] == "test")
	setcookie("TestCookie2", "there",time()+3600);
*/

/*
if($_GET['test5'] == "test5")
{
	echo "<p>" . JURI::current() . "</p>";
}
*/

/*
if ($user->username == "BradM")
{
	$unique_article_word_count = strip_tags($article->introtext);
	$unique_article_word_count = strtolower($unique_article_word_count);
        $unique_article_word_count = str_word_count($unique_article_word_count,1);
	$unique_article_word_count = array_unique($unique_article_word_count);
	echo "<pre>"; print_r($unique_article_word_count); echo "</pre>";
	echo "<pre>" . count($unique_article_word_count); echo "</pre>";
}
*/

?>






<?

// ------------------------------------------------------------------------------------------------
// load items at the bottom of the page to improve page loading
// ------------------------------------------------------------------------------------------------

?>


<script>
$(document).ready(function() {
  $("#mod-search-searchword").focus();
});
</script>



<script src="//<? echo $cdn_subdomain; ?>/support/templates/supportcentertemplate/js/combined.js?v=2016052509" type="text/javascript"></script>

<!-- <div name='853_overlay_join_community' id='853_overlay_join_community'></div> -->




<script type="text/javascript">
                    var launchBoldChat = function() {
                window.open('<? echo $boldchat_url_to_open_with_js; ?>&url=' + escape(document.location.href), '<? echo $boldchat_popup_name; ?>', 'toolbar=0,scrollbars=1,location=0,statusbar=0,menubar=0,resizable=1,width=640,height=650');

                        <? echo $google_set_account_by_author . "\n"; ?>
                        _gaq.push(['_trackEvent', 'chat-by-ip', 'launch-by-ip', '<? echo $_SERVER['HTTP_X_FORWARDED_FOR']; ?>']);

                        _gaq.push(['_setAccount', 'UA-1501988-1']);
                        _gaq.push(['_trackEvent', 'chat', 'launch', 'support center']);
                        _gaq.push(['_trackEvent', 'chat-by-ip', 'launch-by-ip', '<? echo $_SERVER['HTTP_X_FORWARDED_FOR']; ?>']);
                        trackAnchorClickSC("trackAnchorClickChatSC");
            }
        </script>



<script type="text/javascript">
$(document).ready(function() {
    $(".std_ss").fancybox({
          helpers: {
              title : {
                  type : 'float'
              }
          }
      });
});
</script>

<!-- onboarding scheduling -->
<?php /*<script type='text/javascript'>
	jQuery(document).ready(function() {
		jQuery('a.schedOnboarding').fancybox({
			'transitionIn'  :  'elastic',
			'transitionOut'  :  'elastic',
			'speedIn'    :  600,
			'speedOut'    :  200,
			'overlayShow'  :  true,
			'centerOnScroll':true,
			'titleShow' : false,
			'easingIn' : 'easeOutBack',
			'easingOut' : 'easeInBack'
		});
	});
</script> */ ?>



<?

/**
 * combined ajax calls
 * only load the items below if this is an article
 */

// article feedback
$ajax_script_article_feedback = "";
if ($joption == "com_content" AND $jview == "article" AND is_numeric($jid) AND "enabled" == "enabled")
	$ajax_script_article_feedback = "
			// article feedback
			jQuery('#user_ip').val(data.user_ip);
			jQuery('#timestamp_n_id').val(data.timestamp_n_id);";

// overlay - join the community
$ajax_script_overlay_join = "
			// overlay join
			jQuery('#853_overlay_join_community').html(data.overlay_join);";

// increase hits
$ajax_script_increase_hits = "";
if (    ($joption == "com_content" AND $jview == "article" AND is_numeric($jid) ) OR
        ($joption == "com_communitysupport" AND $jview == "show_question" AND is_numeric($jid) ) OR
        ($joption == "com_pup" AND $jview == "article" AND is_numeric($jid) )
        )
	$ajax_script_increase_hits = "
			// increase hits
			jQuery('#page_views').html(data.page_views);";

// latest news
$ajax_latest_news = "
	if(data.latest_news != '') {
		// latest news
		jQuery('#latest_news_items').html(data.latest_news);
		jQuery('#latest_news').slideToggle('fast');
	}
";

if("enable" == "enable")
{
        echo "
<script type='text/javascript'>
	jQuery.post(
		'/support/includes/combined_ajax_calls.php',
		{
			task:'show_overlay',
			option:'$joption',
	                view:'$jview',
        	        id:'$jid',
			guest:'" . $user->guest . "'
		},
		function(data,status){
			$ajax_script_article_feedback
			$ajax_script_overlay_join
			$ajax_script_increase_hits
			$ajax_latest_news
		},
		'json'
	);
</script>
        ";
}






/**
 * FIX - httpd.conf in search caused 501.
 */
echo "
<script type='text/javascript'>
	jQuery('#search_in_header').live('submit', searchSubmit);
	function searchSubmit(e) {
		var txt = document.forms['search_in_header'].getElementById('mod-search-searchword').value;
		txt = txt.replace('httpd.conf','httpdconf');
		document.forms['search_in_header'].getElementById('mod-search-searchword').value = txt;
	}
</script>
";






/**
 * javascript to keep "comments" fixed on the page
 */
echo "
<script type='text/javascript'>
	var DfixComments = jQuery('#fixComments');
	var vTop = DfixComments.offset().top - parseFloat(DfixComments.css('margin-top').replace(/auto/, 0));
	jQuery(window).scroll(function (event) {
		var y = jQuery(this).scrollTop();
		if (y >= vTop) {
			DfixComments.css({'position': 'fixed', 'top': '10px','right': '50%','margin': '0px -455px 0px 0px'});
		} else {
			DfixComments.css({'position': 'relative', 'top': 'auto'});
		}
	});
</script>
";






/**
 * fixed alerts for staff
 */
if( $user->groups[8] == 8 AND "a" == "a")
{
	// are we closing or locking an item?
	switch($_POST['dashboard_staff_action'])
	{
		case "lock":
			$query = "UPDATE #__staff_alerts SET `lock_time` = CURRENT_TIMESTAMP, `lock_user` = " . $user->id . " WHERE `id` = " . $_POST['staff_alert_id'] . " LIMIT 1;";
			$db->setQuery($query);
			$db->execute();
			break;
		case "close":
			$query = "UPDATE #__staff_alerts SET `complete_time` = CURRENT_TIMESTAMP WHERE `lock_user` = " . $user->id . " AND `id` = " . $_POST['staff_alert_id'] . " LIMIT 1;";
                        $db->setQuery($query);
                        $db->execute();
			break;
	}

        echo "
	<script type='text/javascript'>

		jQuery( 'body' ).dblclick(function() {
			jQuery('#staff_8_dashboard').slideToggle('fast');
		});
		function toggle_staff_8_dashboard() {
			jQuery('#staff_8_dashboard').slideToggle('fast');
		}

		// IF the window is active, refresh the dashboard
                // view-source:http://dystroy.org/demos/vis-en.html
		reset_dashboard = setInterval(function(){
			var vis = (function(){
				var stateKey, eventKey, keys = {
					hidden: 'visibilitychange',
					webkitHidden: 'webkitvisibilitychange',
					mozHidden: 'mozvisibilitychange',
					msHidden: 'msvisibilitychange'
				};
				for (stateKey in keys) {
					if (stateKey in document) {
						eventKey = keys[stateKey];
						break;
					}
				}
				return function(c) {
					if (c) document.addEventListener(eventKey, c);
					return !document[stateKey];
				}
			})();

			// http://stackoverflow.com/questions/4249809/reload-an-iframe-with-jquery
			if( vis() == true)
			{
				var iframe = document.getElementById('dashboard_iframe');
				iframe.src = iframe.src;
			}
		},60000);
	</script>
	<style>
		div#staff_8_dashboard {
			position:fixed;
			top:0px;
			right:10px;
			height:100%;
			background:#fff;
		}
		div#staff_8_dashboard iframe {
			width:400px;
			display:block;
			border:0px;
		}
		div.close-dashboard {
                	position:fixed;
			top:0px;
			right:0px;
			width:30px;
			height:30px;
			background:url(/support/templates/supportcentertemplate/images/fancybox/fancybox.png) -40px 0;
			cursor:pointer;
			z-index:1103
		}
	</style>
	<div class='close-dashboard' onClick='toggle_staff_8_dashboard()'></div>
	<div name='staff_8_dashboard' id='staff_8_dashboard'>";

#		 <iframe src='https://www.inmotionhosting.com/support/bradinternaltools/latest_keywords.php?time=" . time() . "&url=" . addslashes($_SERVER['REQUEST_URI']) . "&option=$joption&view=$jview&id=$jid' style='height:50%;' scrolling='auto'></iframe>

echo "		<iframe name='dashboard_iframe' id='dashboard_iframe' class='dashboard' src='//www.inmotionhosting.com/support/gadgets/dashboard/dashboard.php?request_uri=" . urlencode($_SERVER['REQUEST_URI']) . "&user_id=" . $user->id . "&brand=imh' style='height:100%;width:425px;'></iframe>
	</div>
        ";
}


?>


<script type='text/javascript'>
jQuery('a[href*=#]:not([href=#])').click(function() {
    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') 
        || location.hostname == this.hostname) {

        var target = jQuery(this.hash);
        target = target.length ? target : jQuery('[name=' + this.hash.slice(1) +']');
           if (target.length) {
             jQuery('html,body').animate({
                 scrollTop: target.offset().top
            }, 1000);
            return false;
        }
    }
});
</script>



<script type="text/javascript">(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "http://forms.aweber.com/form/80/1702357380.js";
    fjs.parentNode.insertBefore(js, fjs);
    }(document, "script", "aweber-wjs-vwhe4fkd5"));
</script>

</body>
</html>

